### ISSUE TITLE
Make all public structs opaque

### ISSUE THREAD

**Issue by mcatanzaro** [WebPlatformForEmbedded/WPEBackend#15]
We should make structs in the public API opaque in order to make it possible to add new members without breaking the ABI. E.g.:

```
struct wpe_input_keyboard_event {
    uint32_t time;
    uint32_t keyCode;
    uint32_t unicode;
    bool pressed;
    uint8_t modifiers;
};
```

Instead of exposing the contents of the struct, we would expose getter and setter functions: `wpe_input_keyboard_event_get_time()`, `wpe_input_keyboard_event_set_time()`, etc.

Since this is a bigger change, I don't think it has to block the first release, but we should do it before a 1.0 release IMO.

**Comment by mcatanzaro** [comment]
> Since this is a bigger change, I don't think it has to block the first release, but we should do it before a 1.0 release IMO.

Discussed this with Zan. We won't do it for the 0.1 API. Consider again before releasing a 1.0 API version.

**Comment by aperezdc** [comment]
After another round of discussion between myself and @carlosgcampos the conclusion is that doing this would prevent allocating event structs in the stack (which is fast and convenient) and would incur hitting dynamic allocation every time an event is passed around.

We won't be doing this for the time being.

**Comment by carlosgcampos** [comment]
That's actually @zdobersek reasoning, not mine. I still think structs should be opaque to ensure we can modify them in the future without breaking the API/ABI. I'm not opposed to close this anyway, hopefully we won't need to add more fields to events.

**Comment by aperezdc** [comment]
We can always reopen this later if needed, of course.
