### ISSUE TITLE
Make 0.2.0 or 0.1.1 release

### ISSUE THREAD

**Issue by carlosgcampos** [WebPlatformForEmbedded/WPEBackend#20]
I don't know the convention for release numbers, but we need a new release for https://bugs.webkit.org/show_bug.cgi?id=186841

**Comment by aperezdc** [comment]
The change is backwards-compatible, so I think version 0.1.1 would work well here. If we have an agreement about that, I can cut a release (prepare tarballs, test them, make the announcement, and so on).

**Comment by carlosgcampos** [comment]
I don't mind the release number, but I wouldn't expect a 0.2 version to be incompatible. It's major, minor.micro|patch. So what I normally do in projects where I use this approach is increasing micro|patch version for bugfix releases, the minor version for releases including new api or new features and major versions for versions incompatible with previous ones, or doing major changes in the codebase to deserve a new major number.

**Comment by aperezdc** [comment]
For the record, using 0.2.0 is fine by me as well. If nobody is against, I'll go ahead and make the release by Friday.

**Comment by aperezdc** [comment]
[Tag pushed](https://github.com/WebPlatformForEmbedded/WPEBackend/releases/tag/0.2.0), and the tarballs are available [at the usual spot](https://wpewebkit.org/releases/). In moment I will have the release news committed to [Igalia/wpewebkit.org](https://github.com/Igalia/wpewebkit.org) and send the announcement to the mailing list.

**Comment by aperezdc** [comment]
The announcements are now live as well:

- https://wpewebkit.org/release/wpebackend-0.2.0.html
- https://lists.webkit.org/pipermail/webkit-wpe/2018-July/000024.html

I think we can close this, feel free to reopen if there's something wrong or missing (hopefully not!)

**Comment by kraj** [comment]
library versions should change major version for ABI changes, otherwise it should remain same. see
https://autotools.io/libtool/version.html
